limit: 25
pause_seconds: 0.34
create_tables: true
force_reprocess: false
abstract_text_dir: data/articles/abstracts
full_text_dir: data/articles/full_text

aws_region: us-west-2
dynamodb_endpoint_url: http://localhost:8000
reviews_table: reviews
outcomes_table: outcomes
articles_table: articles
